'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("ListView.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Adult Man.
        '''</summary>
        Friend ReadOnly Property AMResult() As String
            Get
                Return ResourceManager.GetString("AMResult", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Adult Woman.
        '''</summary>
        Friend ReadOnly Property AWResult() As String
            Get
                Return ResourceManager.GetString("AWResult", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please fill the empty fields..
        '''</summary>
        Friend ReadOnly Property EmptyFields() As String
            Get
                Return ResourceManager.GetString("EmptyFields", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Female.
        '''</summary>
        Friend ReadOnly Property FemaleGender() As String
            Get
                Return ResourceManager.GetString("FemaleGender", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please select a row to delete..
        '''</summary>
        Friend ReadOnly Property InvalidDeleteText() As String
            Get
                Return ResourceManager.GetString("InvalidDeleteText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Delete Error!.
        '''</summary>
        Friend ReadOnly Property InvalidDeleteTitle() As String
            Get
                Return ResourceManager.GetString("InvalidDeleteTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please select a row to update..
        '''</summary>
        Friend ReadOnly Property InvalidUpdateText() As String
            Get
                Return ResourceManager.GetString("InvalidUpdateText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Update Error!.
        '''</summary>
        Friend ReadOnly Property InvalidUpdateTitle() As String
            Get
                Return ResourceManager.GetString("InvalidUpdateTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Male.
        '''</summary>
        Friend ReadOnly Property MaleGender() As String
            Get
                Return ResourceManager.GetString("MaleGender", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Old Man.
        '''</summary>
        Friend ReadOnly Property OMResult() As String
            Get
                Return ResourceManager.GetString("OMResult", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Old Woman.
        '''</summary>
        Friend ReadOnly Property OWResult() As String
            Get
                Return ResourceManager.GetString("OWResult", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Young Lady Adult.
        '''</summary>
        Friend ReadOnly Property YLAResult() As String
            Get
                Return ResourceManager.GetString("YLAResult", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Young Lady.
        '''</summary>
        Friend ReadOnly Property YLResult() As String
            Get
                Return ResourceManager.GetString("YLResult", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Young Man Adult.
        '''</summary>
        Friend ReadOnly Property YMAResult() As String
            Get
                Return ResourceManager.GetString("YMAResult", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Young Man.
        '''</summary>
        Friend ReadOnly Property YMResult() As String
            Get
                Return ResourceManager.GetString("YMResult", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
